# makefile.m32 - Ming32 makefile.

NAME   = bmp3d

CC     = gcc
CFLAGS = -mwindows
LIBS   = -L../ -lmingw32 -lSDL -lSDLmain -lSDL_ttf

all: bmp3d.c
	$(CC) bmp3d.c -o ../$(NAME).exe $(CFLAGS) $(LIBS)
